spring:
  application:
    name: ${APP_NAME}
    keycloak_realm_name: ${KEYCLOAK_REALM_NAME}
    keycloak_client_id: ${KEYCLOAK_CLIENT_ID}
    keycloak_url: ${KEYCLOAK_URL}
    keycloak_admin_email: ${KEYCLOAK_ADMIN_EMAIL}
    keycloak_admin_password: ${KEYCLOAK_ADMIN_PASSWORD}
    vapi_public_key: ${VAPI_PUBLIC_KEY}
    vapi_private_key: ${VAPI_PRIVATE_KEY}

  frontend:
    url: ${FRONTEND_URL}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:5MB}
      max-request-size: ${MAX_REQUEST_SIZE:5MB}

server:
  port: ${SERVER_PORT:8080}

logging:
  file:
    name: ${LOG_FILE_PATH:logs/app.log}